FROM python:3.10-slim

RUN useradd -m -u 1000 appuser && \
    apt-get update && apt-get install -y \
    wget \
    xz-utils \
    redis-tools \
    && rm -rf /var/lib/apt/lists/*

# Install latest FFmpeg static build
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/**

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt


COPY . .

RUN chown -R appuser:appuser /app
USER appuser

CMD ["celery", "-A", "app.thumbnail", "worker", "--pool=solo", "--loglevel=INFO", "-E", "-Q", "thumbnail_queue"]