services:
  maria-db:
    image: mariadb:11.7.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: toctik
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -uroot -prootpass -e 'SELECT 1;'"]
      interval: 3s
      timeout: 5s
      retries: 30
      start_period: 15s
    
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - redis_network
    ports:
      - "6379:6379"

#  video-processing-service:
#    build:
#      context: ./video-processing-service
#    container_name: video-processing-service
#    ports:
#      - "8001:8000"
#    volumes:
#      - ./video-processing-service:/app
#    depends_on:
#      - redis
#    environment:
#      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
#      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
#      - S3_SECRET_KEY=${S3_SECRET_KEY}
#      - S3_BUCKET=${S3_BUCKET}
#      - S3_REGION=${S3_REGION}
#      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
#      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}

networks:
  redis_network:

volumes:
  db_data:

