apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/counter
    type: DirectoryOrCreate
