apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-authentication-service
  labels:
    app: user-authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-authentication-service
  template:
    metadata:
      labels:
        app: user-authentication-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/bipasapradhan/user-authentication-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: UMS_DB_IP
              value: "maria-db"
            - name: UMS_DB_PORT
              value: "3306"
            - name: UMS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: UMS_DB_PASSWORD
            - name: UMS_DB_NAME
              value: "toctik"
            - name: UMS_DB_USERNAME
              value: "dev"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
