apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processing-service
  template:
    metadata:
      labels:
        app: video-processing-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: video-processing-service
          image: ghcr.io/bipasapradhan/video-processing-service:latest
          ports:
            - containerPort: 80
          env:
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: r2-secret
                  key: CLOUDFLARE_R2_ENDPOINT
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-secret
                  key: CLOUDFLARE_R2_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-secret
                  key: CLOUDFLARE_R2_SECRET_KEY
            - name: S3_REGION
              value: "auto"
            - name: S3_BUCKET
              value: "toktikp2"
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: celery-secret
                  key: CELERY_BROKER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: celery-secret
                  key: CELERY_RESULT_BACKEND
            - name: TZ
              value: "Asia/Bangkok"
          volumeMounts:
            - name: counter-volume
              mountPath: /app/counter
      volumes:
        - name: counter-volume
          persistentVolumeClaim:
            claimName: counter-pvc
