apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunking-worker
  labels:
    app: chunking-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chunking-worker
  template:
    metadata:
      labels:
        app: chunking-worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
      - name: wait-for-redis
        image: busybox
        command:
          - sh
          - -c
          - |
            until nc -z redis 6379; do
              echo "Waiting for Redis..."
              sleep 2
            done

      containers:
        - name: chunking-worker
          image: ghcr.io/bipasapradhan/chunking-service:latest
          command: ["celery"]
          args:
            [
              "-A",
              "app.chunking",
              "worker",
              "--pool=solo",
              "--loglevel=INFO",
              "-E",
              "-Q",
              "chunking_queue",
            ]
          env:
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: r2-secret
                  key: CLOUDFLARE_R2_ENDPOINT
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-secret
                  key: CLOUDFLARE_R2_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-secret
                  key: CLOUDFLARE_R2_SECRET_KEY
            - name: S3_REGION
              value: "auto"
            - name: S3_BUCKET
              value: "toktikp2"
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: celery-secret
                  key: CELERY_BROKER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: celery-secret
                  key: CELERY_RESULT_BACKEND
            - name: TZ
              value: "UTC"
