apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: wait-for-redis
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z redis 6379; do
                echo "Waiting for Redis..."
                sleep 2
              done
      containers:
        - name: websocket
          image: ghcr.io/bipasapradhan/websocket-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: redis-config
            - secretRef:
                name: jwt-secret
