apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: websocket
          image: ghcr.io/bipasapradhan/websocket-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: redis-config
