name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push User Authentication Service (multi-arch)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/bipasapradhan/user-authentication-service:latest \
            -f user-authentication-service/Dockerfile \
            --push \
            user-authentication-service/

      - name: Build and Push Frontend (multi-arch)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/bipasapradhan/frontend-toctik:latest \
            -f frontend/Dockerfile \
            --push \
            frontend/

      - name: Build and Push Video Service (multi-arch)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/bipasapradhan/video-service:latest \
            -f video-service/Dockerfile \
            --push \
            video-service/

      - name: Build and Push Convert Service (multi-arch)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/bipasapradhan/convert-service:latest \
            -f convert_service/Dockerfile_convert \
            --push \
            convert_service/

      - name: Build and Push Chunking Service (multi-arch)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/bipasapradhan/chunking-service:latest \
            -f chunking_service/Dockerfile_chunking \
            --push \
            chunking_service/

      - name: Build and Push Thumbnail Service (multi-arch)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/bipasapradhan/thumbnail-service:latest \
            -f thumbnail_service/Dockerfile_thumbnail \
            --push \
            thumbnail_service/

      - name: Build and Push Video Processing Service (multi-arch)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/bipasapradhan/video-processing-service:latest \
            -f video_processing_service/Dockerfile \
            --push \
            video_processing_service/

      - name: Build and Push Websocket Service (multi-arch)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/bipasapradhan/websocket-service:latest \
            -f web-socket/Dockerfile \
            --push \
            web-socket/
