name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service:
          - name: user-authentication-service
            context: user-authentication-service
            dockerfile: user-authentication-service/Dockerfile
            image: ghcr.io/bipasapradhan/user-authentication-service
          - name: frontend-toctik
            context: frontend
            dockerfile: frontend/Dockerfile
            image: ghcr.io/bipasapradhan/frontend-toctik
          - name: video-service
            context: video-service
            dockerfile: video-service/Dockerfile
            image: ghcr.io/bipasapradhan/video-service
          - name: convert-service
            context: convert_service
            dockerfile: convert_service/Dockerfile_convert
            image: ghcr.io/bipasapradhan/convert-service
          - name: chunking-service
            context: chunking_service
            dockerfile: chunking_service/Dockerfile_chunking
            image: ghcr.io/bipasapradhan/chunking-service
          - name: thumbnail-service
            context: thumbnail_service
            dockerfile: thumbnail_service/Dockerfile_thumbnail
            image: ghcr.io/bipasapradhan/thumbnail-service
          - name: video-processing-service
            context: video_processing_service
            dockerfile: video_processing_service/Dockerfile
            image: ghcr.io/bipasapradhan/video-processing-service
          - name: websocket-service
            context: web-socket
            dockerfile: web-socket/Dockerfile
            image: ghcr.io/bipasapradhan/websocket-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push ${{ matrix.service.name }} (multi-arch)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ matrix.service.image }}:latest \
            -f ${{ matrix.service.dockerfile }} \
            ${{ matrix.service.context }} \
            --push

